# Generated by Django 5.0.3 on 2024-03-30 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('service_name', models.CharField(max_length=50)),
                ('service_catg', models.CharField(choices=[('Workers', 'Worker'), ('Machinerys', 'Machinery'), ('Vehicles', 'Vehicles')], max_length=10)),
                ('service_disc', models.CharField(max_length=240)),
                ('skill', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('charge_type', models.CharField(choices=[('Hour', 'Hr'), ('Day', 'Day'), ('Km', 'Km')], default='Day', max_length=10)),
                ('service_img', models.ImageField(default='', upload_to='home/images')),
                ('register_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
