# Generated by Django 5.0.3 on 2024-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='slug',
            field=models.SlugField(blank=True, default='asdf', max_length=500),
            preserve_default=False,
        ),
    ]
