# Generated by Django 5.0.3 on 2024-03-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_advertise_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='seller_name',
            new_name='user',
        ),
    ]
