# Generated by Django 5.0.3 on 2024-04-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_seller_name_advertise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquirys', to='posts.advertise')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
