# Generated by Django 5.0.3 on 2024-04-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquirys', to='posts.advertise'),
        ),
    ]
