# Generated by Django 5.0.3 on 2024-04-06 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_inquiry_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='work_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
