# Generated by Django 5.0.3 on 2024-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_inquiry_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_mobile',
            field=models.BigIntegerField(default=12345, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='work_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
