# Generated by Django 5.0.3 on 2024-04-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_inquiry_inquiry_mobile_alter_inquiry_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_mobile',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('posted_by', models.CharField(max_length=100)),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.advertise')),
            ],
            options={
                'ordering': ('post_date',),
            },
        ),
    ]
