# Generated by Django 5.0.3 on 2024-04-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_inquiry_inquiry_mobile_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='post_date',
            new_name='created',
        ),
    ]
