# Generated by Django 5.0.3 on 2024-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_reports_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='document',
            field=models.ImageField(blank=True, default='', null=True, upload_to='users/images'),
        ),
    ]
