# Generated by Django 5.0.3 on 2024-04-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_reports_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='document',
        ),
    ]
