# Generated by Django 5.0.3 on 2024-03-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
