# Generated by Django 5.0.3 on 2024-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
