# Generated by Django 5.0.3 on 2024-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_gender_alter_profile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_user.jpg', upload_to='users/%Y/%M/%d'),
        ),
    ]
