# Generated by Django 5.0.3 on 2024-04-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_seller_name_advertise_user'),
        ('users', '0016_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquirys', to='posts.advertise'),
        ),
    ]
