# Generated by Django 5.0.3 on 2024-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
