# Generated by Django 4.0.5 on 2022-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contacts_delete_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('send_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='contacts',
        ),
    ]
