# Generated by Django 4.0.5 on 2022-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_catg', models.CharField(max_length=50)),
                ('product_Disc', models.CharField(max_length=240)),
                ('price', models.IntegerField()),
                ('seller_img', models.ImageField(upload_to='home/images')),
                ('product_img', models.ImageField(default='', upload_to='home/images')),
                ('register_date', models.DateField()),
            ],
        ),
    ]
