# Generated by Django 4.2.7 on 2024-02-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
