# Generated by Django 4.2.7 on 2024-03-10 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='dob',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='skill',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='register_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 3, 11, 3, 23, 31, 836710)),
        ),
    ]
