# Generated by Django 5.0.3 on 2024-03-28 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='charge_type',
            field=models.CharField(choices=[('Hour', 'Hr'), ('Day', 'Day'), ('Km', 'Km')], default='Day', max_length=10),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='skill',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='product_catg',
            field=models.CharField(choices=[('Workers', 'Worker'), ('Machinerys', 'Machinery'), ('Vehicles', 'Vehicles')], max_length=10),
        ),
    ]
