# Generated by Django 4.2.7 on 2024-03-10 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_seller_info_dob_seller_info_gender_seller_info_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='register_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 3, 11, 3, 30, 50, 804240)),
        ),
    ]
