# Generated by Django 4.2.7 on 2024-03-10 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_seller_info_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='register_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 3, 11, 3, 32, 31, 450174)),
        ),
    ]
