# Generated by Django 4.2.7 on 2024-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_seller_info_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='dob',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
