# Generated by Django 4.2.7 on 2024-03-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_seller_info_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='register_date',
            field=models.DateField(null=True),
        ),
    ]
