# Generated by Django 4.2.7 on 2024-03-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_seller_info_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_info',
            name='dob',
        ),
    ]
