# Generated by Django 4.2.7 on 2024-03-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_seller_info_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_info',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='seller_info',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='seller_info',
            name='status',
        ),
    ]
