# Generated by Django 4.2.7 on 2024-03-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_seller_info_gender_remove_seller_info_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='register_date',
            field=models.DateField(),
        ),
    ]
