# Generated by Django 4.2.7 on 2024-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_seller_info_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='register',
            field=models.DateField(default=15.553846153846154),
            preserve_default=False,
        ),
    ]
