# Generated by Django 4.2.7 on 2024-03-10 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_seller_info_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_info',
            name='register',
        ),
        migrations.AddField(
            model_name='seller_info',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
