# Generated by Django 4.2.7 on 2024-03-10 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_seller_info_register_seller_info_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_info',
            name='date_added',
        ),
        migrations.AddField(
            model_name='seller_info',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
