# Generated by Django 4.2.7 on 2024-03-10 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_seller_info_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
