# Generated by Django 4.2.7 on 2024-03-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_seller_info_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='gender',
            field=models.CharField(default='test', max_length=6),
            preserve_default=False,
        ),
    ]
