# Generated by Django 4.2.7 on 2024-03-10 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_seller_info_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='skill',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_info',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='product_catg',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Machinery', 'Machinery'), ('Vehicles', 'Vehicles')], max_length=10),
        ),
    ]
