# Generated by Django 4.2.7 on 2024-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_seller_info_skill_seller_info_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='age',
            field=models.IntegerField(default='null'),
            preserve_default=False,
        ),
    ]
