# Generated by Django 4.2.7 on 2024-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_seller_info_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
