# Generated by Django 4.2.7 on 2024-03-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_seller_info_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='age',
            field=models.CharField(default='20', max_length=50),
            preserve_default=False,
        ),
    ]
