# Generated by Django 4.2.7 on 2024-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_seller_info_charge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='charge_type',
            field=models.CharField(choices=[('Hour', 'Hr'), ('Day', 'Day'), ('Km', 'Km')], default='Day', max_length=10),
        ),
    ]
